### ISSUE TITLE
Passage nom de membre en argument

### ISSUE THREAD

**Issue by arthurdeschamps** [arthurdeschamps/swift-exercises#1]
Est-il possible de passer un "nom" de membre de structure à une fonction et d'ensuite y accéder pour différentes structures, de manière simple?

Ex:
`struct S1 { let ppte: Int }; struct1(ppte: 30);`
`struct S2 { let s1: S1); struct2(ppte: 1); }`
`func accessPpt(_ ppte: Any) -> Int {return struct1.ppte + struct2.s1.ppte }`
`accessPpt(ppte)`

Pour une description plus concrète de mon problème (lié au tp):
[stackoverflow question](http://stackoverflow.com/questions/42459318/how-can-i-access-a-struct-member-by-passing-its-name-as-a-function-parameter-in)

**Comment by saucisson** [comment]
Ca semble compliqué. Tu devrais passer une fonction permettant d'extraire le champ demandé, au lieu du nom du champ.
Désolé pour la réponse tardive.

**Comment by arthurdeschamps** [comment]
Mais le problème est que le champ est dans différentes structures avec des "accès" différents.

Bon, j'ai déjà réglé le problème en passant à la fonction directement la valeur du champ, mais je voulais juste éviter de faire ça parce que j'appelle 5 fois une fonctions avec à chaque fois les même types d'arguments et juste le nom du champ qui change:

```
attack: computeStat(self, base: self.species.base_values.attack, effort: self.effort_values.attack, individual: self.individual_values.attack, stat_name: "attack"),
defense: computeStat(self, base: self.species.base_values.defense, effort: self.effort_values.defense, individual: self.individual_values.defense, stat_name: "defense"),
special_attack: computeStat(self, base: self.species.base_values.special_attack, effort: self.effort_values.special_attack,  individual: self.individual_values.special_attack, stat_name: "special_attack"),
special_defense: computeStat(self, base: self.species.base_values.special_defense, effort: self.effort_values.special_defense, individual: self.individual_values.special_defense, stat_name: "special_defense"), 
speed: computeStat(self, base: self.species.base_values.speed, effort: self.effort_values.speed, individual: self.individual_values.speed, stat_name: "speed")```

**Comment by saucisson** [comment]
@kyouko-taiga vois-tu une solution plus élégante ?

**Comment by kyouko-taiga** [comment]
On ne peux pas passer une chaine de texte pour obtenir une propriété (à la `__getattr__` de python) sans passer par la réflection our Objective-C. Je déconseille fortement ces deux approches!

Si j'ai bien compris le problème, le plus simple serait de modifier comment les propriétés sont stored fans la struct, et de remplacer l'API existent par des computed properties (en gros, on reimplemented le fonctionnement de `__dict__` en python).

```swift
struct S {

    var props = [String: Any]()

    var propInt: Int {
        // Safe forced-unwrapping because of our initializer.
        get { return self.props["propInt"] as! Int }

        // Don't add this line if propInt should be a constant.
        set { self.props["propInt"] = newValue }
    }

    var propString: String {
        get { return self.props["propString"] as! String }
        set { self.props["propString"] = newValue }
    }

    func getAttr<T>(_ attr: String) -> T? {
        return self.props[attr] as? T
    }

    init(propInt: Int, propString: String) {
        self.props["propInt"] = propInt
        self.props["propString"] = propString
    }

}

var s = S(propInt: 2, propString: "Hello")
print(s.propString) // Prints "Hello"
s.propString = "World"
print(s.props["propString"] as! String) // Prints "World"
print(s.getAttr("propInt")! * 2) // Prints "4"
```

**Comment by arthurdeschamps** [comment]
Merci pour la réponse.

J'ai suivi ton conseil et modifié la structure en elle-même en ajoutant une fonction `getStat(stat_name: String)` , ce qui me permet d'appeler la fonction `computeStat()` avec seulement une chaine de caractères et un pokemon, ce qui est beaucoup plus simple.

Je ferme donc l'issue.
